// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCf1IWMngdFJjVmtypzcuOW7rOlOwLMFE',
    appId: '1:715221615315:web:2c2dba41474d0a29608a26',
    messagingSenderId: '715221615315',
    projectId: 'royserfirebase',
    authDomain: 'royserfirebase.firebaseapp.com',
    storageBucket: 'royserfirebase.firebasestorage.app',
    measurementId: 'G-MJGTT7MDPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Zsao9d2VJn5nG9PX7qbazItazaVtqCM',
    appId: '1:715221615315:android:acd2c94a2edca3fe608a26',
    messagingSenderId: '715221615315',
    projectId: 'royserfirebase',
    storageBucket: 'royserfirebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCf1IWMngdFJjVmtypzcuOW7rOlOwLMFE',
    appId: '1:715221615315:web:ad88396038d534db608a26',
    messagingSenderId: '715221615315',
    projectId: 'royserfirebase',
    authDomain: 'royserfirebase.firebaseapp.com',
    storageBucket: 'royserfirebase.firebasestorage.app',
    measurementId: 'G-L7FJHVKQ0S',
  );

}